root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/docs/zeroclipboard-bundle
        permanent: false

locale:
    pattern: /en
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/docs/zeroclipboard-bundle
        permanent: false

docs:
    pattern: /en/docs
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/docs/zeroclipboard-bundle
        permanent: false

zeroclipboard:
    resource: "@ZeroClipboardBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/docs/zeroclipboard-bundle
    requirements:
        _locale: en|fr|de
